### ISSUE TITLE
Keda Kafka trigger throwing error, no functions invoked

### ISSUE THREAD

**Issue by zjpiazza** [fission/keda-connectors#132]
**Fission/Kubernetes version**
<pre>
$ fission --version
client: v1.18.0
server: v1.18.0
</pre>
<pre>
$ kubectl version
Client Version: v1.24.9
Kustomize Version: v4.5.4
Server Version: v1.24.9-gke.3200
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
GKE 

**Describe the bug**
Unable to create Keda Message Queue Trigger (Kafka) for Python function

**To Reproduce**
- Install fission v1.18.0
- Create Python 3.10 environment
`fission -n [custom-namespace] env create --name [env-name] --image fission/python-env-3.10 --builder fission/python-builder-3.10`
- Create Python function
`fission -n [custom-namespace] fn create --name [func-name] --env [env-name] --code main.py`
- Create Kafka trigger
`fission -n [custom-namespace] mqt create --name [trigger-name] --function [func-name] --mqtype kafka --mqtkind keda --topic [topic] --resptopic [resp-topic] --errortopic [error-topic] --maxretries 3 --metadata bootstrapServers=[servers] --metadata consumerGroup=[consumer-group] --metadata topic=[topic]  --cooldownperiod=30 --pollinginterval=5`

**Expected result**
Function should be triggered based on messages being sent to the specified topic

**Actual result**
Error message shown in the `mqtrigger-kafka` pod:
```
{"level":"info","ts":"2023-03-23T15:34:20.870Z","caller":"otel/provider.go:50","msg":"OTEL_EXPORTER_OTLP_ENDPOINT not set, skipping Opentelemtry tracing"}
{"level":"info","ts":"2023-03-23T15:34:20.870Z","caller":"crd/client.go:105","msg":"Waiting for CRDs to be installed"}
W0323 15:34:21.013634       1 warnings.go:70] spec.template.spec.containers[0].env[9].name: duplicate name "TOPIC"
{"level":"error","ts":"2023-03-23T15:34:21.017Z","caller":"mqtrigger/scalermanager.go:102","msg":"Failed to create ScaledObject","error":"the server could not find the requested resource","stacktrace":"github.com/fission/fission/pkg/mqtrigger.mqTriggerEventHandlers.func1.1\n\tpkg/mqtrigger/scalermanager.go:102"}
```

**Screenshots/Dump file**
[fission-dump_1679585295.zip](https://github.com/fission/keda-connectors/files/11052703/fission-dump_1679585295.zip)

**Additional context**
**values.yaml**
```
additionalFissionNamespaces:
- cdc
analytics: true
analyticsNonHelmInstall: false
authentication:
  authUriPath: null
  authUsername: admin
  enabled: false
  jwtExpiryTime: null
  jwtIssuer: fission
  jwtSigningKey: serverless
builderNamespace: ""
builderPodSpec:
  enabled: false
  podSpec:
    securityContext:
      fsGroup: 10001
      runAsGroup: 10001
      runAsNonRoot: true
      runAsUser: 10001
buildermgr:
  resources: {}
  securityContext:
    enabled: true
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
busyboxImage: busybox
canaryDeployment:
  enabled: false
  resources: {}
  securityContext:
    enabled: true
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
controller:
  enabled: false
  resources: {}
  securityContext:
    enabled: true
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
controllerPort: 31313
createNamespace: true
debugEnv: false
defaultNamespace: default
enableIstio: false
executor:
  adoptExistingResources: false
  container: {}
  newdeploy: {}
  objectReaperInterval: 5
  podReadyTimeout: 300s
  poolmgr: {}
  priorityClassName: ""
  resources: {}
  securityContext:
    enabled: true
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
  serviceAccountCheck:
    enabled: true
    interval: 0
  terminationMessagePath: ""
  terminationMessagePolicy: ""
fetcher:
  image: fission/fetcher
  imageTag: v1.18.0
  resource:
    cpu:
      limits: ""
      requests: 10m
    mem:
      limits: ""
      requests: 16Mi
functionNamespace: ""
gaTrackingID: UA-196546703-1
grafana:
  dashboards:
    enable: false
  namespace: monitoring
image: fission/fission-bundle
imagePullSecrets: []
imageTag: v1.18.0
influxdb:
  enabled: false
  image: influxdb:1.8
kafka:
  authentication:
    tls:
      caCert: ""
      enabled: false
      insecureSkipVerify: false
      userCert: ""
      userKey: ""
  brokers: cdc-cluster-kafka-brokers.cdc.svc.cluster.local:9202
  enabled: true
  version: 3.4.0
kubewatcher:
  resources: {}
  securityContext:
    enabled: true
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
logger:
  enableSecurityContext: false
  fluentdImage: fluent/fluent-bit
  fluentdImageRepository: index.docker.io
  fluentdImageTag: 1.8.8
  influxdbAdmin: admin
  podSecurityPolicy:
    additionalCapabilities: null
    enabled: false
mqt_keda:
  connector_images:
    aws_sqs:
      image: fission/keda-aws-sqs-http-connector
      tag: v0.10
    awskinesis:
      image: fission/keda-aws-kinesis-http-connector
      tag: v0.10
    gcp_pubsub:
      image: fission/keda-gcp-pubsub-http-connector
      tag: v0.5
    kafka:
      image: fission/keda-kafka-http-connector
      tag: v0.11
    nats_jetstream:
      image: fission/keda-nats-jetstream-http-connector
      tag: v0.2
    nats_steaming:
      image: fission/keda-nats-streaming-http-connector
      tag: v0.12
    rabbitmq:
      image: fission/keda-rabbitmq-http-connector
      tag: v0.10
    redis:
      image: fission/keda-redis-http-connector
      tag: v0.3
  enabled: true
  resources: {}
openTelemetry:
  otlpCollectorEndpoint: ""
  otlpHeaders: ""
  otlpInsecure: true
  propagators: tracecontext,baggage
  tracesSampler: parentbased_traceidratio
  tracesSamplingRate: "0.1"
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  size: 8Gi
podMonitor:
  additionalPodMonitorLabels: {}
  enabled: false
  namespace: ""
postInstallReportImage: fission/reporter
pprof:
  enabled: false
preUpgradeChecks:
  enabled: true
  image: fission/pre-upgrade-checks
  imageTag: v1.18.0
priorityClassName: ""
prometheus:
  serviceEndpoint: ""
pullPolicy: IfNotPresent
repository: index.docker.io
router:
  deployAsDaemonSet: false
  displayAccessLog: false
  priorityClassName: ""
  resources: {}
  roundTrip:
    disableKeepAlive: false
    keepAliveTime: 30s
    maxRetries: 10
    timeout: 50ms
    timeoutExponent: 2
  securityContext:
    enabled: true
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
  svcAddressMaxRetries: 5
  svcAddressUpdateTimeout: 30s
  terminationMessagePath: ""
  terminationMessagePolicy: ""
  unTapServiceTimeout: 3600s
  useEncodedPath: false
routerPort: 31314
routerServiceType: LoadBalancer
runtimePodSpec:
  enabled: false
  podSpec:
    securityContext:
      fsGroup: 10001
      runAsGroup: 10001
      runAsNonRoot: true
      runAsUser: 10001
serviceMonitor:
  additionalServiceMonitorLabels: {}
  enabled: false
  namespace: ""
serviceType: ClusterIP
storagesvc:
  archivePruner:
    enabled: true
    interval: 60
  resources: {}
  securityContext:
    enabled: true
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File
timer:
  resources: {}
  securityContext:
    enabled: true
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
webhook:
  caBundlePEM: ""
  certManager:
    enabled: false
  crtPEM: ""
  keyPEM: ""
  resources: {}
  securityContext:
    enabled: true
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001

```
